version: '2'
services:
    learnsql-app:
        image: learnsql
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://learnsql-mysql:3306/learnsql?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://learnsql-elasticsearch:9200
        ports:
            - 8080:8080
    learnsql-mysql:
        extends:
            file: mysql.yml
            service: learnsql-mysql
    learnsql-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: learnsql-elasticsearch
